<?php
// Generated by `npm run api-password`. Verifies the shared password for api/placements.php.
// A .php file so the server executes it instead of serving its contents. Holds a salt and a
// PBKDF2-SHA256 hash — never the password itself — so committing it is safe.
return [
  'iterations' => 210000,
  'salt' => 'F7pxDPTkHzmMWRP3qctdaQ==',
  'hash' => 'g657Tw7l6hoFRUNznhej96g417mcHk790+gzKcACcM0=',
];
